- name: Prepare
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - gpg
        update_cache: yes
      changed_when: false
