---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Collect service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      var: ansible_facts.services['polkadot.service']

  - name: check service
    ansible.builtin.assert:
      that: ansible_facts.services['polkadot.service'].state == 'running'